config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root to: 'posts#index'

  resources :posts
  resources :subscribers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  #This validates presence of title, and makes sure that the length is not more than 140 words

  validates :title, presence: true, length: {maximum: 140}

  #This validates presence of body

  validates :body, presence: true
  validates :image, presence: true

  CATEGORIES = ['Parier', 'Investir', 'Bons Plans', 'Economiser']
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :firstname, :name, :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  #configure permitted parameters for devise
  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me, :avatar, :avatar_cache]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:edit, :update, :show, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :authenticate_admin!, except: [:index, :show]

  # Index action to render all posts
  def index
    if params[:category]
      @posts = Post.all.where(category: params[:category]).reverse_order
    else
      @posts = Post.all.reverse_order
    end
    # @posts = Post.all.reverse_order
    @subscriber = Subscriber.new
  end

  # def parier
  #   @posts = Post.all.where
  # end

  # New action for creating post
  def new
    @post = Post.new
  end

  # Create action saves the post into database
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Successfully created post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error creating new post!"
      render :new
    end
  end

  # Edit action retrives the post and renders the edit page
  def edit
  end

  # Update action updates the post with the new information
  def update
    if @post.update_attributes(post_params)
      flash[:notice] = "Successfully updated post!"
      redirect_to post_path(@post)
    else
      flash[:alert] = "Error updating post!"
      render :edit
    end
  end

  # The show action renders the individual post after retrieving the the id
  def show
    @subscriber = Subscriber.new
  end

  # The destroy action removes the post permanently from the database
  def destroy
    if @post.delete
      flash[:notice] = "Successfully deleted post!"
      redirect_to posts_path
    else
      flash[:alert] = "Error updating post!"
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :category)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @subscriber = Subscriber.new
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    if @subscriber.save
      redirect_to root_path, notice: "Merci de votre inscription!"
    else
      redirect_to root_path, notice: "Il semblerait qu'il y ait eu un souci lors de votre inscription à la newsletter"
    end
  end

  private

  def subscriber_params
    params.require(:subscriber).permit(:firstname, :name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.html.erb
<div class="col-sm-offset-4 col-sm-4 col-xs-12">
  <% if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
  <% end %>

  <% if devise_mapping.omniauthable? %>
    <% resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag "favicon/favicon.ico" %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mind Your Money</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- Render navigation bar -->
  <%= render "shared/navbar" %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>


</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:" %>
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
          <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.input :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :image, class: "form-control" %>
    <%= f.input :image_cache, as: :hidden %>
  </div>

  <div class="form-group">
    <%= f.input :category, collection: Post::CATEGORIES, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.input :body, :as => :ckeditor, input_html: {:ckeditor => {:toolbar => 'FULL'}}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

<%#= Rajouter champ pour image post dans index (soit ça recadre l'index et set la dimension pour la partie 'post', soit rajouter 2 champs)  %>

app/views/posts/edit.html.erb
<div class="container-fluid">
  <div class="container-money">
    <h2>Edit Post</h2>

    <%= render "posts/form" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <div class="container-money">
    <h2 class="size23px padding15-45 margin-bottom20">ARTICLES RÉCENTS</h2>
    <div class="container-post">
    <% @posts.each do |post| %>
      <div class="container-post-side col-sm-12 col-md-6">
        <div class="index-image">
          <%= link_to cl_image_tag(post.image), post_path(post) %>
        </div>
        <div class="index-title">
          <h3 class="size18px"><%= link_to post.title, post_path(post), class: "no-decoration" %></h3>
        </div>
        <p class="date-money"><%= post.created_at.strftime('%b %d, %Y') %> | <i><%= link_to post.category, posts_path(category: post.category), class: "no-decoration-color-grey" %></i></p>
        <div class="body-post">
          <%= raw post.body.truncate(381, separator: /\n/, omission: '') %>
        </div>
        <%= link_to "LIRE PLUS", post_path(post), class: "add-turquoise" %>
        <br>
      <% if admin_signed_in? %>
        <%= link_to "Show", post_path(post), class: "white-font" %>
        <%= link_to "Edit", edit_post_path(post), class: "white-font" %>
        <%= link_to "Delete", post_path(post), class: "white-font", data: {:confirm => "Are you sure?"}, method: :delete %>
      <% end %>

      </div>
    <% end %>
    </div>
  </div>
</div>

<div class="container-money">
  <div class="padding25-45 margin-top100">
    <%= render "subscribers/index" %>
    <div class="gray-line"></div>
<!--     <div class="donate-crypto">
      <p>Donate <span class="bold-style">BTC</span>: 3HqVn5TmMBUXgPdV8zbe1hcctuVMSXGqjH</p>
      <p>Donate <span class="bold-style">ETH</span>: 0x667eaD1Cb228E86bD41Ec27B208C9869faCFe889</p>
      <p>Donate <span class="bold-style">LTC</span>: LVa4VA7TdYjhgcCghDpvQM4FSF6iiV7vHo</p>
    </div> -->
  </div>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
  <div class="container-money">
    <h2>Create New Post</h2>

    <%= render "posts/form" %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container-fluid">
  <div class="container-money-show padding15-45">
    <div class="titre-date">
      <h2 class="size23px margin-bottom30"><%= @post.title.upcase %></h2>
      <p class="date-money"><%= @post.created_at.strftime('%b %d, %Y') %></p>
    </div>
    <div class="show-image margin-bottom15">
      <%= cl_image_tag @post.image %>
    </div>

    <div class="show-image show-font">
      <%= raw @post.body %>
    </div>
  </div>
</div>

<div class="container-money">
  <div class="padding25-45 margin-top100">
    <%= render "subscribers/index" %>
    <div class="gray-line"></div>
<!--     <div class="donate-crypto">
      <p>Donate <span class="bold-style">BTC</span>: 3HqVn5TmMBUXgPdV8zbe1hcctuVMSXGqjH</p>
      <p>Donate <span class="bold-style">ETH</span>: 0x667eaD1Cb228E86bD41Ec27B208C9869faCFe889</p>
      <p>Donate <span class="bold-style">LTC</span>: LVa4VA7TdYjhgcCghDpvQM4FSF6iiV7vHo</p>
    </div> -->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- <div class="turquoise-line"></div> -->
<div class="container-money padding15-45">
  <div class="navbar-money amiko-13">
    <div class="navbar-money-left">
      <%= link_to root_path, class: "navbar-brand-2" do %>
        <%#= image_tag "MLOGO.png" %>
        <%= image_tag "MindYOURMoney.png" %>
      <% end %>
    </div>
    <div class="navbar-money-middle">
      <% Post::CATEGORIES.each do |category_name| %>
        <%= link_to category_name, posts_path(category: category_name) %>
      <% end %>
      <!-- <a href=""><span>Parier</span></a>
      <%#= link_to post.category, root_path(category: category) %>
      <a href=""><span>Investir</span></a>
      <a href=""><span>Bons Plans</span></a>
      <a href=""><span>Économiser</span></a> -->
      <a href=""><span>Contact</span></a>
    </div>
    <div class="navbar-money-right">
      <i class="fas fa-search"></i>
    </div>
  </div>
</div>








<%#= link_to 'Home', root_path, class: "white-font" %>
  <% if admin_signed_in? %>
  <!--This block is only visible to signed in admins -->
    <%= link_to 'New Post', new_post_path, class: "white-font" %>
    <%= link_to 'My Account', edit_admin_registration_path, class: "white-font"  %>
    <%= link_to 'Logout', destroy_admin_session_path, class: "white-font", :method => :delete %>
  <!-- The block ends here -->
  <% else %>
    <%#= link_to 'Login', new_admin_session_path, class: "white-font" %>
  <% end %>

app/views/subscribers/_index.html.erb
<center>
  <div class="newsletter-form">
    <center>
      <h3>SOYEZ TENU AU COURANT !</h3>
      <h6>Inscrivez-vous à la newsletter pour ne rien manquer.</h6>
      <%= form_for @subscriber do |f| %>
        <div class="newsletter-field">
          <%= f.text_field :firstname, placeholder: "Prénom", class: "newsletter-name" %>
          <%= f.text_field :name, placeholder: "Nom", class: "newsletter-name" %>
        </div>
        <div class="newsletter-field">
          <%= f.text_field :email, placeholder: "Adresse Mail", class: "newsletter-mail" %>
        </div>
        <div>
          <%= f.submit "SIGN UP", class: "newsletter-submit" %>
        </div>
      <% end %>
    </center>
  </div>
</center>